// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkvvapewwauvpjbwletg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrdnZhcGV3d2F1dnBqYndsZXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyOTg1ODMsImV4cCI6MjA1Njg3NDU4M30.y08w-XdY7YAOBsYcD0C1KSlzmoVOl8p1Vq3ek0U9oM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);